MYSQL_USER=root MYSQL_PASSWORD=root MYSQL_SERVICE_HOST=127.0.0.1 MYSQL_SERVICE_PORT=30306 MYSQL_DATABASE=configurations JAVA_DEBUG=true JAVA_DEBUG_PORT=8788 mvn wildfly-jar:dev -f ./configurations-rest/

